const ProductsDetailsActionsTypes = {
    FETCH_PRODUCTS_DETAILS_START: 'FETCH_PRODUCTS_DETAILS_START',
    FETCH_PRODUCTS_DETAILS_SUCCESS: 'FETCH_PRODUCTS_DETAILS_SUCCESS',
    FETCH_PRODUCTS_DETAILS_FAILURE: 'FETCH_PRODUCTS_DETAILS_FAILURE'
}


export default ProductsDetailsActionsTypes;
